version: "3"
services:
  web:
    build: .
    image: kaehops/webaudioeditor
    ports:
      - "80:3000"
    links:
      - mongo
    container_name: webaudio
  mongo:
    image: mongo
    ports:
      - "38128:27017"
    container_name: mongo
